import streamlit as st
from langchain.chains import LLMChain
from langchain_community.chat_models.tongyi import ChatTongyi
from langchain_core.messages import HumanMessage
import time

with st.sidebar:
    st.title('The contents below are generated by ali-qwen.')
    "[API Document of qwen](https://help.aliyun.com/zh/dashscope/developer-reference/api-details?spm=a2c4g.11186623.0.i48)"

st.title('📝Streaming Chat Bot powered by ChatTongyi.')
def generate_response(text):
    chatLLM = ChatTongyi(model_name="qwen-plus", streaming=True)
    resp = chatLLM.stream([HumanMessage(content=text)], streaming=True)
    for r in resp:
        yield r.content


with st.form("my_form"):
    text = st.text_area("Enter text:", "Ask me something.")
    submitted = st.form_submit_button("Submit")

    if submitted:
        st.write_stream(generate_response(text))